title: Drowse-Lab
description: "Drowse-Labのブログと開発記録"
url: "https://drowse-lab.github.io"
baseurl: "/Drowse-Lab"

markdown: kramdown
theme: minima
highlighter: rouge
future: true

collections:
  posts:
    output: true
  diary:
    output: true
    permalink: /diary/:year/:month/:day/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
  - scope:
      path: ""
      type: "diary"
    values:
      layout: diary-entry
      sitemap: true

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-feed
  - jekyll-paginate

author: Drowse-Lab members
subtitle: ""

include:
  - blog.html
  - diary.html
